---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины.
  - Сайт должен иметь мобильную версию.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и
    оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя..
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Нет возможности авторизации пользователя.
  - Нет возможности указывать количество выбираемого товара.
  - Неровная вёрстка количества товаров в корзине.
  - При заказе товара в всплывающем окне заказа не ровная вёрстка товара.
  - При заказе товара нет окна с подтверждением покупки товара
  - Нет возможность искать товары по ключевому слову на русском языке

