---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову иликатегории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Сайт должен иметь мобильную версию.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге

non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя..
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен быть SPA

implicit:
  - На сайте должна быть авторизации пользователя.
  - На сайте должна быть возможность указывать количество выбираемого товара
  - На сайте должна быть кнопка сброса всех флитров
  - Должна быть возможность искать товар по ключевому слову на русском языке
  - После оформления товара корзина должна автоматически очищаться
  - Для покупки товара должна быть авторизация пользователя
  - Пользователь должен иметь возможность при добавление в корзину указывать количество товаров 
  - На сайте должна быть возможность смотреть изборжения в полноэкранном режиме
  - На сайте должна быть возможность оценивания товаров 
