---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
 
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя..
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен иметь мобильную версию.

implicit:
  - На сайте должна быть авторизации пользователя.
  - На сайте должна быть возможность указывать количество выбираемого товара.
  - Неровная вёрстка количества товаров в корзине.
  - При заказе товара в всплывающем окне заказа не ровная вёрстка товара.
  - При заказе товара нет окна с подтверждением покупки товара
  - Должна быть возможность искать товар по ключевому слову на русском языке
  - После оформления товара корзина должна автоматически очищаться
  - Пользователь должен быть авторизован для оформаления заказа 
